productos =[ {
    id : 1,
    timestamp:"",
    nombre:"cafe nespresso suave",
    descripcion:"",
    codigo:010101,
    foto: "eCommerceBackend-CamilaIrigoyen/imagenes/cafe1",
    precio:"550",
    stock:5,

},
{id : 2,
    timestamp:"",
    nombre:"cafe nespresso mediano",
    descripcion:"",
    codigo:020202,
    foto: "eCommerceBackend-CamilaIrigoyen/imagenes/cafe2",
    precio:"650",
    stock:5,

},
{id : 3,
    timestamp:"",
    nombre:"cafe nespresso fuerte",
    descripcion:"",
    codigo:030303,
    foto: "eCommerceBackend-CamilaIrigoyen/imagenes/cafe3",
    precio:"750",
    stock:5,}]